### ISSUE TITLE
Hitting Item frame and Ghast fireball

### ISSUE THREAD

**Issue by Sirosix96** [UsainSrht/HealthBar#1]
Error in console when hitting an Itemframe and Ghast Fireball:
[ERROR]: Could not pass event EntityDamageByEntityEvent to Healthbar v1.1
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_19_R2.entity.CraftItemFrame cannot be cast to class org.bukkit.entity.Damageable (org.bukkit.craftbukkit.v1_19_R2.entity.CraftItemFrame and org.bukkit.entity.Damageable are in unnamed module of loader java.net.URLClassLoader @ba8a1dc)...

**Comment by UsainSrht** [comment]
I'll fix it when I have time. For now, you can add them to blacklisted entity types.

**Comment by Sirosix96** [comment]
The Error from the Itemframe occurs only when a item is in the frame and you want to get it out of it.

**Comment by UsainSrht** [comment]
Fixed in 7e185cb15c79169665688fbcfc9e1b2b2e6239c8
